// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBNGEQc6DaeEZhyAXb0Y36FHLPq4uQ2dM',
    appId: '1:768350372879:web:13d7a6f27f26f55e344f7a',
    messagingSenderId: '768350372879',
    projectId: 'chat-8d1c7',
    authDomain: 'chat-8d1c7.firebaseapp.com',
    storageBucket: 'chat-8d1c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm-ayQNX_ebAvkaG0rW1eFFSqOHpk1XSk',
    appId: '1:768350372879:android:c0d0bd2c61931684344f7a',
    messagingSenderId: '768350372879',
    projectId: 'chat-8d1c7',
    storageBucket: 'chat-8d1c7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBNGEQc6DaeEZhyAXb0Y36FHLPq4uQ2dM',
    appId: '1:768350372879:web:2f4f8b067c535c65344f7a',
    messagingSenderId: '768350372879',
    projectId: 'chat-8d1c7',
    authDomain: 'chat-8d1c7.firebaseapp.com',
    storageBucket: 'chat-8d1c7.firebasestorage.app',
  );
}
